### ISSUE TITLE
Plans for pypi ?

### ISSUE THREAD

**Issue by vindarel** [marekjm/diacli#1]
Hi ! 

Do you have any plans to put diacli on pypi ? It would ease its test, use and spread dramatically.

thanks

**Comment by marekjm** [comment]
Well, I never really thought about it. As you can see, it hasn't been updated for a long time (two years) now. I wrote it when I didn't have X available, and then kinda dropped it. I don't even remember when was the last time I logged in to Diaspora using this tool, to be frank...

I assume you have downloaded and tried to use it?

**Comment by vindarel** [comment]
Ok, that's what I guessed but I had to ask !

I tried, but the installation was weird and not working, and since the pypi version isn't working for me I didn't push further.
